/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.Controlador;
import Modelo.Producto;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Nicolas Castaño
 */
public class ContenedorF extends javax.swing.JPanel {
    
    private DefaultListModel<Producto> modeloProductos;
    private DefaultListModel<Producto> modeloCarrito;
    private VentanaPrincipal ventana;

    /**
     * Creates new form ContenedorF
     */
    public ContenedorF(VentanaPrincipal ventana) {
        initComponents();
        this.ventana = ventana;
        
        inicializarModelos();
        cargarProductos();
        configurarListeners();


        comprar.addActionListener(e -> {
        ventana.mostrarPanel(new DatosCompra(ventana));
        });
    }
    
    private void inicializarModelos() {
        modeloProductos = new DefaultListModel<>();
        modeloCarrito = new DefaultListModel<>();

        listaProductos.setModel(modeloProductos);
        listaCarrito.setModel(modeloCarrito);
    }

    private void cargarProductos() {
        Controlador c = new Controlador();

        for (Producto p : c.obtenerProductos()) {
            modeloProductos.addElement(p);
        }
    }

    private void configurarListeners() {

        agregar.addActionListener(e -> {
            Producto seleccionado = listaProductos.getSelectedValue();
            if (seleccionado != null) {
                modeloCarrito.addElement(seleccionado);
                actualizarTotal();
            }
        });

        quitar.addActionListener(e -> {
            Producto seleccionado = listaCarrito.getSelectedValue();
            if (seleccionado != null) {
                modeloCarrito.removeElement(seleccionado);
                actualizarTotal();
            }
        });

        limpiar.addActionListener(e -> {
            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Deseas limpiar el carrito?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                modeloCarrito.clear();
                actualizarTotal();
            }
        });
        
        verDetalles.addActionListener(e -> {
            Producto seleccionado = listaProductos.getSelectedValue();
            if (seleccionado != null) {

                ImageIcon icon = new ImageIcon(
                    getClass().getResource("/img/" + seleccionado.getImagen())
                );

                JOptionPane.showMessageDialog(
                    this,
                    seleccionado.getNombre() + "\nPrecio: $" + seleccionado.getPrecio(),
                    "Detalles",
                    JOptionPane.INFORMATION_MESSAGE,
                    icon
                );
            }
        });


    }
    
    private void actualizarTotal() {
        int suma = 0;
        int tamaño = modeloCarrito.getSize();

        for (int i = 0; i < tamaño; i++) {
            suma += modeloCarrito.get(i).getPrecio();
        }

        total.setText("Total a pagar: $" + suma + "   |   Items: " + tamaño);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCarrito = new javax.swing.JList<>();
        agregar = new javax.swing.JButton();
        verDetalles = new javax.swing.JButton();
        quitar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        comprar = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        titulo.setText("CATÁLOGO DE PRODUCTOS");

        jLabel2.setText("Productos disponibles");

        jLabel3.setText("Carrito");

        listaProductos.setModel(new javax.swing.DefaultListModel<Producto>());
        jScrollPane1.setViewportView(listaProductos);

        listaCarrito.setModel(new javax.swing.DefaultListModel<Producto>());
        jScrollPane2.setViewportView(listaCarrito);

        agregar.setText("Agregar Producto");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        verDetalles.setText("Detalles");

        quitar.setText("Quitar Producto");

        limpiar.setText("Limpiar Carrito");

        total.setText("Total a pagar: ");

        comprar.setText("Comprar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(agregar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comprar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(limpiar)
                                        .addComponent(quitar)))))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verDetalles)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(verDetalles)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total)
                            .addComponent(comprar))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitar)
                        .addGap(18, 18, 18)
                        .addComponent(limpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarActionPerformed

                                               

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JList<Producto> listaCarrito;
    private javax.swing.JList<Producto> listaProductos;
    private javax.swing.JButton quitar;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel total;
    private javax.swing.JButton verDetalles;
    // End of variables declaration//GEN-END:variables
}
